/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unifacs.a3_engsoftware.JAVA.view;

import com.unifacs.a3_engsoftware.JAVA.Usuario.UsuarioController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author alex.santos
 */
 public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameLogin = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelSenha = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();
        jButtonRegistrese = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNameLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabelNameLogin.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNameLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNameLogin.setText("LOGIN");
        getContentPane().add(jLabelNameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 50));

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 0, 0));
        jLabelUsuario.setText("Usuário");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 100, 30));

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 190, 30));

        jLabelSenha.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSenha.setText("Senha");
        getContentPane().add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 100, 30));
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 190, 30));

        jButtonEntrar.setBackground(new java.awt.Color(153, 153, 153));
        jButtonEntrar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jButtonEntrar.setForeground(new java.awt.Color(255, 0, 0));
        jButtonEntrar.setText("Entrar");
        jButtonEntrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        jButtonEntrar.setContentAreaFilled(false);
        jButtonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 120, -1));

        jButtonRegistrese.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButtonRegistrese.setForeground(new java.awt.Color(255, 0, 0));
        jButtonRegistrese.setText("Registre-se");
        jButtonRegistrese.setBorder(null);
        jButtonRegistrese.setContentAreaFilled(false);
        jButtonRegistrese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRegistrese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistreseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrese, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 80, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/unifacs/a3_engsoftware/resources/plano_de_fundo.jpg"))); // NOI18N
        jLabel2.setInheritsPopupMenu(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 540, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        if(jTextFieldUsuario.getText().matches("") || jPasswordFieldSenha.getText().matches("")){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
        } else {
            try{
                UsuarioController login = new UsuarioController();
                login.loginUsuario(this);

                if(login.getAcesso() == true){
                    if(login.getVfsenha() == true){
                        this.dispose();
                        ListaEventos menu = new ListaEventos();
                        menu.setVisible(true);
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Senha Incorreta"); 
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Usuário Não Encontrado\nTente Realizar um Cadastro!");
                }
            } catch (SQLException sql){
                JOptionPane.showMessageDialog(rootPane, "Erro ao Entrar, Tente Novamente!\nErro SQLCode: "+sql.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed
//Usuário não localizado!\nRealize Um Cadastro
    public JPasswordField getjPasswordFieldSenha() {
        return jPasswordFieldSenha;
    }

    public void setjPasswordFieldSenha(JPasswordField jPasswordFieldSenha) {
        this.jPasswordFieldSenha = jPasswordFieldSenha;
    }

    public JTextField getjTextFieldUsuario() {
        return jTextFieldUsuario;
    }

    public void setjTextFieldUsuario(JTextField jTextFieldUsuario) {
        this.jTextFieldUsuario = jTextFieldUsuario;
    }

    private void jButtonRegistreseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistreseActionPerformed
       Cadastro telaCadastro = new Cadastro();
       telaCadastro.setVisible(true);
    }//GEN-LAST:event_jButtonRegistreseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonRegistrese;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNameLogin;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

}
